routes/web.php
<?php

    /*
    |--------------------------------------------------------------------------
    | Web Routes
    |--------------------------------------------------------------------------
    |
    | Here is where you can register web routes for your application. These
    | routes are loaded by the RouteServiceProvider within a group which
    | contains the "web" middleware group. Now create something great!
    |
    */

    Route::get('/', [
        'as'   => 'home',
        'uses' => function () {
            return view('home');
        },
    ]);
    Route::get('/random', function () {
        return view('random');
    });

    include base_path('routes/web/auth.php');
    include base_path('routes/web/awards.php');
    include base_path('routes/web/backups.php');
    include base_path('routes/web/committee.php');
    include base_path('routes/web/contact.php');
    include base_path('routes/web/election.php');
    include base_path('routes/web/equipment.php');
    include base_path('routes/web/events.php');
    include base_path('routes/web/logs.php');
    include base_path('routes/web/media.php');
    include base_path('routes/web/members.php');
    include base_path('routes/web/page.php');
    include base_path('routes/web/quotes.php');
    include base_path('routes/web/resources.php');
    include base_path('routes/web/training.php');
    include base_path('routes/web/users.php');

app/Models/Events/Crew.php
<?php

namespace App\Models\Events;

use App\Models\Users\User;
use bnjns\WebDevTools\Laravel\Traits\ChecksIfJoined;
use bnjns\WebDevTools\Laravel\Traits\ValidatableModel;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Crew extends Model
{
    use ValidatableModel, ChecksIfJoined;

    /**
     * The validation rules for a crew role's attributes.
     *
     * @var array
     */
    protected static $ValidationRules = [
        'user_id'    => 'required|exists:users,id',
        'name'       => 'nullable|required_if:core,1',
        'guest_name' => 'required',
    ];

    /**
     * The validation rules for a crew role's attributes.
     *
     * @var array
     */
    protected static $ValidationMessages = [
        'user_id.required'    => 'Please select a member',
        'user_id.exists'      => 'Please select a member',
        'name.required_if'    => 'Please enter a role title',
        'guest_name.required' => 'Please enter the guest\'s name',
    ];

    /**
     * Disable timestamps
     *
     * @var bool
     */
    public $timestamps = false;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'event_crew';

    /**
     * The attributes fillable by mass assignment.
     *
     * @var array
     */
    protected $fillable = [
        'event_id',
        'user_id',
        'name',
        'em',
        'confirmed',
        'guest_name',
    ];

    /**
     * Define the attributes that need type-casting.
     *
     * @var array
     */
    protected $casts = [
        'em'        => 'boolean',
        'confirmed' => 'boolean',
    ];

    /**
     * The attributes that should be visible when converted to an array.
     *
     * @var array
     */
    protected $visible = [
        'id',
        'user_id',
        'name',
        'em',
        'confirmed',
        'guest_name',
        'core',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'core',
    ];

    /**
     * Define the foreign key relationship with the event.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function event()
    {
        return $this->belongsTo('App\Models\Events\Event');
    }

    /**
     * Define the foreign key relationship with the user.
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\Models\Users\User');
    }

    /**
     * Get event manager crew roles.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     */
    public function scopeEm(Builder $query)
    {
        $query->where('em', true);
    }

    /**
     * Get core crew roles.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     */
    public function scopeCore(Builder $query)
    {
        $query->member()
              ->where('name', '<>', null);
    }

    /**
     * Get general crew roles.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     */
    public function scopeGeneral(Builder $query)
    {
        $query->member()
              ->where('name', null);
    }

    /**
     * Get member crew roles (not guests).
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     */
    public function scopeMember(Builder $query)
    {
        $query->where('user_id', '<>', null);
    }

    /**
     * Get guests.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     */
    public function scopeGuest(Builder $query)
    {
        $query->whereNull('user_id');
    }

    /**
     * Filter to crew roles for a specific user.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @param \App\Models\Users\User                $user
     */
    public function scopeForUser(Builder $query, User $user)
    {
        $query->where('user_id', $user->id);
    }

    /**
     * Order the crew by role name, the user name.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     */
    public function scopeOrder(Builder $query)
    {
        if (!$this->alreadyJoined($query, 'users')) {
            $query->select('event_crew.*')
                  ->join('users', 'event_crew.user_id', '=', 'users.id');
        }
        $query->orderBy('event_crew.name', 'ASC')
              ->orderBy('users.surname', 'ASC')
              ->orderBy('users.forename', 'ASC');
    }

    /**
     * Test whether the crew role is for a guest user (non-registered).
     *
     * @return bool
     */
    public function isGuest()
    {
        return $this->user_id === null;
    }

    /**
     * Get the crew member's name.
     *
     * @return mixed
     */
    public function getCrewNameAttribute()
    {
        return $this->isGuest() ? $this->guest_name : $this->user->name;
    }

    /**
     * Get whether the crew role is a core crew.
     *
     * @return bool
     */
    public function getCoreAttribute()
    {
        return (int)($this->name !== null);
    }
}

app/Http/Controllers/Events/CrewController.php
<?php

namespace App\Http\Controllers\Events;

use App\Http\Controllers\Controller;
use App\Logger;
use App\Models\Events\Crew;
use App\Models\Events\Event;
use App\Models\Users\User;
use App\Notifications\Events\HasBeenVolunteered;
use App\Notifications\Events\UserHasVolunteered;
use App\Notifications\Events\VolunteeredToCrew;
use bnjns\LaravelNotifications\Facades\Notify;
use Illuminate\Http\Request;

class CrewController extends Controller
{
    /**
     * Set the basic authentication requirements.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Process the form and create the new crew role.
     *
     * @param                          $eventId
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function store($eventId, Request $request)
    {
        // Authorise
        $this->requireAjax();
        $event = Event::findOrFail($eventId);
        $this->authorize('update', $event);

        return $this->isGuestAction($event, $request) ? $this->storeGuest($event, $request) : $this->storeMember($event, $request);
    }

    /**
     * Update a crew role.
     *
     * @param                          $eventId
     * @param                          $crewId
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function update($eventId, $crewId, Request $request)
    {
        // Authorise all updates
        $this->requireAjax();
        $event = Event::findOrFail($eventId);
        $crew  = $event->crew()
                       ->where('event_crew.id', $crewId)
                       ->firstOrFail();
        $this->authorize('update', $crew);

        if ($request->has('action')) {
            $action = $request->get('action');

            if ($action == 'update-field') {
                return $this->updateField($crew, $request);
            }
        } else {
            if ($this->isGuestAction($event, $request)) {
                return $this->updateGuest($crew, $request);
            } else {
                return $this->updateMember($crew, $request);
            }
        }
    }

    /**
     * @param $eventId
     * @param $crewId
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($eventId, $crewId)
    {
        // Authorise
        $event = Event::findOrFail($eventId);
        $crew  = $event->crew()
                       ->where('event_crew.id', $crewId)
                       ->firstOrFail();
        $this->authorize('delete', $crew);

        // Delete
        $crew->delete();
        Notify::success($crew->isGuest() ? 'Guest removed' : 'Crew role deleted');
        return $this->ajaxResponse($crew->isGuest() ? 'Guest removed' : 'Crew role deleted');
    }

    /**
     * Toggle the volunteering status for the current user.
     *
     * @param                          $eventId
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function toggleVolunteer($eventId, Request $request)
    {
        $this->requireAjax();

        $event = Event::findOrFail($eventId);
        $this->authorize('volunteer', $event);

        if (!$request->user()->isCrew($event)) {
            return $this->volunteer($event, $request);
        } else {
            return $this->unvolunteer($event, $request);
        }
    }

    /**
     * Add a guest to the crew list.
     *
     * @param \App\Models\Events\Event $event
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    private function storeGuest(Event $event, Request $request)
    {
        // Validate
        $fields = ['guest_name'];
        $this->validate($request, Crew::getValidationRules($fields), Crew::getValidationMessages($fields));

        // Create
        $crew = $event->crew()
                      ->create([
                          'user_id'    => null,
                          'name'       => null,
                          'em'         => false,
                          'confirmed'  => $request->has('confirmed'),
                          'guest_name' => clean($request->get('guest_name')),
                      ]);

        Logger::log('event-crew.create', true, $crew->getAttributes());

        Notify::success('Guest added');
        return $this->ajaxResponse('Guest added');
    }

    /**
     * Add a member to the crew list.
     *
     * @param \App\Models\Events\Event $event
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    private function storeMember(Event $event, Request $request)
    {
        $user = User::find($request->get('user_id'));

        // Validate
        $fields = ['user_id', 'name'];
        $this->validate($request, Crew::getValidationRules($fields), Crew::getValidationMessages($fields));

        // Check the member doesn't already have the same crew role
        if ($event->crew()->where('user_id', $request->get('user_id'))->where('name', $request->get('name') ?: null)->count()) {
            return $this->ajaxError(0, 422, $user->forename . ' already has that crew role.');
        }

        // Create
        $crew = $event->crew()
                      ->create([
                          'user_id'   => $request->get('user_id'),
                          'name'      => $request->get('core') ? clean($request->get('name')) : null,
                          'em'        => $request->get('core') ? $request->has('em') : false,
                          'confirmed' => $event->isTracked() ? $request->has('confirmed') : false,
                      ]);

        Logger::log('event-crew.create', true, $crew->getAttributes());

        // Send an email to the user
        User::find($request->get('user_id'))->notify(new HasBeenVolunteered($event));

        Notify::success('Member added to crew');
        return $this->ajaxResponse('Member added to crew');
    }

    /**
     * @param \App\Models\Events\Crew  $crew
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    private function updateField(Crew $crew, Request $request)
    {
        $field = $request->get('field');
        $value = $request->has('value') ? $request->get('value') : false;

        // Validate the request
        $this->validate($request, [
            'field' => [
                'required',
                'in:confirmed',
            ],
        ], [
            'field.required' => 'No field specified',
            'field.in'       => 'No valid field specified',
        ]);

        $crew->update([
            $field => $value,
        ]);
        return $this->ajaxResponse('Field updated');
    }

    /**
     * Update a guest's details.
     *
     * @param \App\Models\Events\Crew  $crew
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    private function updateGuest(Crew $crew, Request $request)
    {
        // Validate
        $fields = ['guest_name'];
        $this->validate($request, Crew::getValidationRules($fields), Crew::getValidationMessages($fields));

        // Update
        $crew->update([
            'confirmed'  => $request->has('confirmed'),
            'guest_name' => clean($request->get('guest_name')),
        ]);

        Notify::success('Guest updated');
        return $this->ajaxResponse('Guest updated');
    }

    /**
     * Update a member's role.
     *
     * @param \App\Models\Events\Crew  $crew
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    private function updateMember(Crew $crew, Request $request)
    {
        // Validate
        $fields = ['name'];
        $this->validate($request, Crew::getValidationRules($fields), Crew::getValidationMessages($fields));

        // Update
        $crew->update([
            'name'      => $request->get('core') ? clean($request->get('name')) : null,
            'em'        => $request->get('core') ? $request->has('em') : false,
            'confirmed' => $crew->event->isTracked() ? $request->has('confirmed') : false,
        ]);

        Notify::success('Crew role updated');
        return $this->ajaxResponse('Crew role updated');
    }

    /**
     * Volunteer to crew an event.
     *
     * @param \App\Models\Events\Event $event
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    private function volunteer(Event $event, Request $request)
    {
        // Create the crew role
        $crew = $event->crew()->create([
            'name'    => null,
            'user_id' => $request->user()->id,
        ]);

        // Notify the user and EM
        if ($event->hasEM()) {
            $event->em->notify(new UserHasVolunteered($crew));
        }
        $request->user()->notify(new VolunteeredToCrew($event));

        Logger::log('event.volunteer', true, $crew->getAttributes());

        // Message
        Notify::success('You have volunteered');
        return $this->ajaxResponse('Volunteered');
    }

    /**
     * Unvolunteer from an event.
     *
     * @param \App\Models\Events\Event $event
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\JsonResponse
     */
    private function unvolunteer(Event $event, Request $request)
    {
        // Disallow unvolunteering from socials
        if ($event->isSocial()) {
            return $this->ajaxError(0, 401, 'You can\'t unvolunteer from a social.');
        }

        // Delete all crew entries
        $event->crew()
              ->where('user_id', $request->user()->id)
              ->delete();

        Logger::log('event.unvolunteer', true, ['event_id' => $event->id, 'user_id', $request->user()->id]);

        Notify::success('You have unvolunteered');

app/Http/Controllers/Events/EmailController.php
<?php

namespace App\Http\Controllers\Events;

use App\Http\Controllers\Controller;
use App\Http\Requests\Events\EmailRequest;
use App\Models\Events\Event;

class EmailController extends Controller
{
    /**
     * Set the basic authentication requirements.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Send an email to the crew.
     * @param                                        $eventId
     * @param \App\Http\Requests\Events\EmailRequest $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store($eventId, EmailRequest $request)
    {
        // Authorise
        $this->requireAjax();
        $event = Event::findOrFail($eventId);
        $this->authorize('update', $event);

        // Create the email object
        $email = $event->emails()->create([
            'sender_id' => $request->user()->id,
            'header'    => clean($request->get('header')),
            'body'      => clean($request->get('body')),
        ]);

        // Send the email to the crew
        return $email->send($request->get('crew'), $request->user());
    }
}

resources/views/events/view/_paperwork.blade.php
<span class="editable"
      data-editable="toggle"
      data-action="{{ route('event.update', ['id' => $event->id]) }}"
      data-field="paperwork.{{ $paperwork }}">
            <span class="fa fa-{{ $event->paperwork[$paperwork] ? 'check' : 'remove' }}"></span>
        </span>

resources/views/events/view/crew.blade.php
<h2>Crew List</h2>

{{-- Crew count --}}
<p class="crew-count">
    @if($event->isSocial())
        {{ $event->countCrew('members') }} members and {{ $event->countCrew('guests') }} guests ({{ $event->countCrew('confirmed') }} paid)
    @elseif($event->isTraining())
        {{ $event->countCrew('em') }} instructors and {{ ($event->countCrew('members') - $event->countCrew('em')) }} attendees
        ({{ $event->countCrew('confirmd') }} attended)
    @else
        {{ $event->countCrew('core') }} core crew and {{ $event->countCrew('general') }} general crew
    @endif
</p>

{{-- Buttons --}}
<div class="top-buttons">
    @can('volunteer', $event)
        <div class="btn-group">
            @if($event->userIsCrew(Auth::user()))
                @if(!$event->isSocial())
                    <button class="btn btn-danger"
                            data-submit-ajax="{{ route('event.volunteer', ['id' => $event->id]) }}"
                            data-redirect="true"
                            data-redirect-location="{{ route('event.view', ['id' => $event->id, 'tab' => 'crew']) }}"
                            type="button">
                        <span class="fa fa-user-times"></span>
                        <span>Unvolunteer</span>
                    </button>
                @endif
            @else
                <button class="btn btn-success"
                        data-submit-ajax="{{ route('event.volunteer', ['id' => $event->id]) }}"
                        @if($event->isSocial())
                        data-submit-confirm="Are you sure you want to sign-up for this social? By signing up you agree to pay any costs, even if you can no longer attend."
                        @endif
                        data-redirect="true"
                        data-redirect-location="{{ route('event.view', ['id' => $event->id, 'tab' => 'crew']) }}"
                        type="button">
                    <span class="fa fa-user-plus"></span>
                    <span>Volunteer</span>
                </button>
            @endif
        </div>
        @endif
        @can('update', $event)
            <div class="btn-group">
                <button class="btn btn-success"
                        data-toggle="modal"
                        data-target="#modal"
                        data-modal-template="event_crew"
                        data-modal-class="modal-sm"
                        data-modal-title="Add Crew Role"
                        data-form-action="{{ route('event.crew.store', ['id' => $event->id]) }}"
                        data-mode="create"
                        type="button">
                    <span class="fa fa-user-plus"></span>
                    <span>Add crew</span>
                </button>
                @if($event->isSocial())
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                    </button>
                    <ul class="dropdown-menu">
                        <li>
                            <button data-toggle="modal"
                                    data-target="#modal"
                                    data-modal-template="event_guest"
                                    data-modal-class="modal-sm"
                                    data-modal-title="Add Guest"
                                    data-form-action="{{ route('event.crew.store', ['id' => $event->id]) }}"
                                    data-mode="create"
                                    type="button">
                                <span class="fa fa-user-secret"></span>
                                <span>Add guest user</span>
                            </button>
                        </li>
                    </ul>
                @endif
            </div>
        @endcan
</div>

{{-- Crew List --}}
<div class="crew-list">
    @if($event->countCrew() > 0)
        <div class="form-static">
            @if($event->hasEM())
            <div class="form-entry">
                <label class="control-label">TEM:</label>
                <div class="editable">{{ $event->em->name }}</div>
            </div>
            @endif
            @foreach($event->crew as $crew_role => $crew_list)
                @if(count($crew_list) > 0)
                    <div class="form-entry">
                        <label class="control-label">{{ $crew_role }}:</label>
                        <div class="form-control-static">
                            @foreach($crew_list as $crew)
                                @can('update', $event)
                                    <div class="editable"
                                         data-toggle="modal"
                                         data-target="#modal"
                                         data-modal-template="{{ $crew->isGuest() ? 'event_guest' : 'event_crew' }}"
                                         data-modal-title="Edit Crew"
                                         data-modal-class="modal-sm"
                                         data-save-action="{{ route('event.crew.update', ['id' => $event->id, 'crewId' => $crew->id]) }}"
                                         data-delete-action="{{ route('event.crew.destroy', ['id' => $event->id, 'crewId' => $crew->id]) }}"
                                         data-form-data="{{ json_encode($crew) }}"
                                         data-mode="edit"
                                         data-editable="true">
                                        @if($event->isTracked())
                                            <span class="editable"
                                                  data-editable="toggle"
                                                  data-action="{{ route('event.crew.update', ['id' => $event->id, 'crewId' => $crew->id]) }}"
                                                  data-field="confirmed">
                                                <span class="fa fa-{{ $crew->confirmed ? 'check' : 'remove' }}"></span>
                                            </span>
                                        @endif
                                        <span>{{ $crew->crew_name }}</span>
                                    </div>
                                @else
                                    <div class="editable">{{ $crew->crew_name }}</div>
                                @endcan
                            @endforeach
                        </div>
                    </div>
                @endif
            @endforeach
        </div>
    @else
        <p>No one is crewing this event yet</p>
    @endif
</div>

resources/views/events/view/details.blade.php
<h2>Event Details</h2>
<div class="form-static">
    <div class="form-entry">
        <label class="control-label">Event Manager:</label>
        <div class="form-control-static">{!! $event->em ? $event->em->name : '<em>&ndash; not yet assigned &ndash;</em>' !!}</div>
    </div>
    <div class="form-entry">
        <label for="type" class="control-label">Type:</label>
        <div class="form-control-static">
            <span class="event-entry tag upper {{ $event->type_class }}">{{ $event->type_string }}</span>
        </div>
    </div>
    @if($event->isEvent())
        <div class="form-entry">
            <label for="client" class="control-label">Client:</label>
            <div class="form-control-static">{{ $event->client }}</div>
        </div>
    @endif
    <div class="form-entry">
        <label for="venue" class="control-label">Venue:</label>
        <p class="form-control-static">{{ $event->venue }}</p>
    </div>
    <div class="form-entry">
        <label for="description" class="control-label">Description:</label>
        <div class="form-control-static description">
            {!! Markdown::convertToHtml($event->description) !!}
        </div>
    </div>
</div>

resources/views/events/view/emails.blade.php
<h2>Event Emails</h2>
@can('update', $event)
    <div class="top-buttons">
        <div class="btn-group">
            <button class="btn btn-success"
                    data-toggle="modal"
                    data-target="#modal"
                    data-modal-template="event_email"
                    data-mode="create"
                    type="button">
                <span class="fa fa-envelope"></span>
                <span>Email crew</span>
            </button>
            <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a href="mailto:{{ implode(',', $event->crew_mailing_list) }}?subject=[Backstage Website] {{ $event->name }}">
                        <span class="fa fa-external-link"></span>
                        <span>Use mail client</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
@endcan
<div class="email-wrapper">
    @forelse($event->emails as $email)
        <div class="email">
            <div class="subject">{{ $email->header }}</div>
            <div class="details">
                <div class="sender">
                    <div class="heading">From</div>
                    <div>{{ $email->sender->name }} ({{ $email->sender->username }})</div>
                </div>
                <div class="date">
                    <div class="heading">Sent</div>
                    <div>{{ $email->created_at->format('h:ia D M Y') }}</div>
                </div>
            </div>
            <div class="body">{!! Markdown::convertToHtml($email->body) !!}</div>
        </div>
    @empty
        <p>There are no crew emails for this event.</p>
    @endif
</div>

resources/views/events/view/paperwork.blade.php
<h2>Event Paperwork</h2>
<div class="paperwork-list">
    {{-- Risk Assessment --}}
    <div class="paperwork">
        @include('events.view._paperwork', ['paperwork' => 'risk_assessment'])
        <div class="name">Risk assessment</div>
        <p class="link{{ $event->paperwork['risk_assessment'] ? ' hidden' : '' }}" data-show="incomplete">
            <span class="fa fa-link"></span>
            <a class="grey" href="{{ config('bts.links.risk_assessment') }}" target="_blank">Risk assessment form</a>
        </p>
    </div>
    {{-- Insurance --}}
    <div class="paperwork">
        @include('events.view._paperwork', ['paperwork' => 'insurance'])
        <div class="name">Insurance</div>
    </div>
    {{-- TEM Finance --}}
    <div class="paperwork">
        @include('events.view._paperwork', ['paperwork' => 'finance_em'])
        <div class="name">TEM finance</div>
    </div>
    {{-- Treasurer Finance --}}
    <div class="paperwork">
        @include('events.view._paperwork', ['paperwork' => 'finance_treas'])
        <div class="name">Treasurer finance</div>
    </div>
    {{-- Event Report --}}
    <div class="paperwork">
        @include('events.view._paperwork', ['paperwork' => 'event_report'])
        <div class="name">Event report</div>
        <p class="link{{ $event->paperwork['event_report'] ? ' hidden' : '' }}" data-show="incomplete">
            <span class="fa fa-link"></span>
            <a class="grey" href="{{ route('event.report', ['id' => $event->id]) }}">Event report form</a>
        </p>
    </div>
</div>